### ISSUE TITLE
Lazy registring

### ISSUE THREAD

**Issue by roganov** [seedofjoy/bazooka#32]
Typically, almost all components live in separate files, therefore
`Baz.register` method call takes the form of
```
Bazooka.register({
  compA: require('/path/to/A'),
  compB: require('/path/to/B'),
  /* ... */
  compZ: require('/path/to/Z')
})
```
This, however, will result in the source code of all components being evaluated on every page, even if the current page needs only a subset of components.

Workaround is simple: just wrap each `require` in a function remembering to account for both `BazComponent.simple` and `BazComponent.universal` component types:
```
Bazooka.register({
  compA: (el) => require('/path/to/A')(el),
  compB: (el) => require('/path/to/B').bazFunc(el),
  /* ... */
  compZ: (el) => require('/path/to/Z')(el)
})
```

Since lazy evaluation is desired in most cases, it might be better to add support for  "lazy registering" to the library API. The API may be similar to:
```
Bazooka.lazyRegister({
  compA: '/path/to/A',
  compB: '/path/to/B',
}, require)
```

**Comment by zemlanin** [comment]
How big is response time boost after lazy wrapping?

Bazooka promotes ES6 Modules system, which requires imports to be done before an actual code execution. I guess it's better to do it via multiple bundles in browserify or via [code splitting](https://webpack.github.io/docs/code-splitting.html) in webpack

**Comment by roganov** [comment]
The win in time obviously depends on the project size, whether there are computation on the module level and changes from page to page. Mostly static pages with little scripting may get a considerable benefit, while on script-heavy pages the difference is barely noticeable.
That said, I was able to reduce the scripting time by ~300ms on some pages.

**Comment by roganov** [comment]
@zemlanin 
Also, I'm not sure I understand you regarding ES6 modules. ES6 spec only defines importing/exporting syntax and it doesn't (yet) specify any programmatic API. You can't use ES6 modules without a module-loading system (CommonJS, AMD, UMD, ect).

**Comment by zemlanin** [comment]
ES6 syntax prevents you from importing inside expressions and other statements. Such as `lazyRequire` function call

**Comment by roganov** [comment]
OK, solved client-side.
