### ISSUE TITLE
Component is not disposed when parent node is removed from a page

### ISSUE THREAD

**Issue by andreymal** [seedofjoy/bazooka#46]
```html
<div id="test1" data-bazooka="test">test1</div>
<div id="test2wrap">
    <div id="test2" data-bazooka="test">test2</div>
</div>

<button id="btn">Killall</button>
```

```javascript
import Baz from 'bazooka';

Baz.register({
  test: function(node) {
    var bazid = node.getAttribute('data-bazid');
    console.log('Attached bazid', bazid);
    return function() {
        console.log('Disposed bazid', bazid);
    }
  }
});

window.btn.onclick = function() {
    window.test1.parentNode.removeChild(window.test1);
    window.test2wrap.parentNode.removeChild(window.test2wrap);
    Baz.refresh();
}
Baz.refresh();
```

Expected output after button click:

```
Attached bazid 0
Attached bazid 1
Disposed bazid 0
Disposed bazid 1
```

Actual output:

```
Attached bazid 0
Attached bazid 1
Disposed bazid 0
```

That's because Bazooka checks `wrapper.__wrapped__.parentNode` and this is not null for `test2` node (`parentNode` is test2wrap, `parentNode.parentNode` is null).

Using `document.body.contains(wrapper.__wrapped__)` gives the expected behavior (not sure if `rootNode` can be used here)

**Comment by zemlanin** [comment]
Wow, thanks for the great looking issue 👍

**Comment by andreymal** [comment]
Looks like `rootNode` cannot be used if `Baz.watch()` is used

Modified example:

```html
<div id="test1" data-bazooka="test">test1</div>
<div id="test2wrap">
    <div id="test2" data-bazooka="test">test2</div>
</div>
<div id="etc"></div>

<button id="btn">Modify</button>
```


```javascript
Baz.register(...);

window.btn.onclick = function() {
    // window.test1.parentNode.removeChild(window.test1);
    // window.test2wrap.parentNode.removeChild(window.test2wrap);
    window.etc.appendChild(document.createElement('div'));
}
Baz.watch();  // !
```

Expected output after click (nothing was removed):

```
Attached bazid 0
Attached bazid 1
```

Actual output:

```
Attached bazid 0
Attached bazid 1
Disposed bazid 0
Disposed bazid 1
```

In this case `Bazooka.refresh(mutation.target);` was called and `rootNode` is `<div class "etc">` and `rootNode.contains(wrapper.__wrapped__)` returns `false`

**Comment by zemlanin** [comment]
It is difficult for me to make sense out of modified example 😞

- What do you mean by "`rootNode` cannot be used if `Baz.watch()` is used"? 
- `rootNode` shouldn't be `<div id="etc">` if `Baz.watch()` was called without arguments

**Comment by andreymal** [comment]
>`rootNode` shouldn't be `<div id="etc">`

But this is exactly `<div id="etc">` ¯\\\_(ツ)\_/¯

![](https://i.imgur.com/foQksIu.gif)

**Comment by zemlanin** [comment]
Oh, got it
